name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      GO_VERSION: 1.16
      GOARCH: amd64
    strategy:
      matrix:
        include:
          - os: macos-latest
            GOOS: darwin
          - os: ubuntu-latest
            GOOS: windows
          - os: ubuntu-latest
            GOOS: linux
          - os: ubuntu-latest
            GOOS: freebsd
          - os: ubuntu-latest
            GOOS: openbsd
          - os: ubuntu-latest
            GOOS: netbsd
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Cache go installer
      uses: actions/cache@v2
      with:
        key: ${{ env.GO_VERSION }}-${{ matrix.os }}-${{ env.GOARCH }}
        path: |
          ~/cache/go${{ env.GO_VERSION }}.${{ matrix.os }}-${{ env.GOARCH }}.tar.gz

    - name: Install deps
      env:
        GOOS: ${{ matrix.GOOS }}
        RUNNER_OS: ${{ matrix.os }}
      run: ./.github/install-go.sh

    - name: Build
      env:
        GOOS: ${{ matrix.GOOS }}
      run: ./.github/build.sh
